"""Voice generation module using VOICEVOX API."""
import os
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parents[1]))
sys.path.append(str(Path(__file__).resolve().parents[2]))

from __future__ import annotations
import json
from pathlib import Path
from typing import Union
import requests

from config.communcation_settings import (
    AUDIO_QUERY_ENDPOINT,
    SYNTHESIS_ENDPOINT,
    SPEAKER_ID_KASUKABE_TSUMUGI,
)


class VoiceGenerator:
    """Class for generating voice audio data using VOICEVOX API.

    This class manages text inputs and their corresponding WAV binary data
    generated by VOICEVOX API.
    """

    def __init__(self, speaker_id: int = SPEAKER_ID_KASUKABE_TSUMUGI):
        """Initialize VoiceGenerator.

        Args:
            speaker_id: VOICEVOX speaker ID to use for voice synthesis.
        """
        self.speaker_id = speaker_id
        self.text_queue: list[str] = []
        self.audio_data_queue: list[bytes] = []

    def generate_push_voice(self, text: Union[str, list[str]]) -> None:
        """Generate voice audio from text and store in queues.

        Accepts a single text string or a list of text strings,
        generates corresponding WAV binary data using VOICEVOX API,
        and appends both text and audio data to internal queues.

        Args:
            text: Single text string or list of text strings to convert to voice.
        """
        # Convert single string to list for uniform processing
        if isinstance(text, str):
            text_list = [text]
        else:
            text_list = text

        # Process each text
        for txt in text_list:
            # Skip empty strings
            if not txt or txt.strip() == "":
                continue

            try:
                # audio_query (API to create a query for speech synthesis)
                res1 = requests.post(
                    AUDIO_QUERY_ENDPOINT,
                    params={'text': txt, 'speaker': self.speaker_id}
                )
                res1.raise_for_status()

                # synthesis (API to synthesize speech from audio query)
                res2 = requests.post(
                    SYNTHESIS_ENDPOINT,
                    params={'speaker': self.speaker_id},
                    data=json.dumps(res1.json())
                )
                res2.raise_for_status()

                # Store text and audio data
                audio_bytes = res2.content
                self.text_queue.append(txt)
                self.audio_data_queue.append(audio_bytes)

            except requests.exceptions.RequestException as e:
                print(f"Failed to generate voice for text '{txt}': {e}")
                continue

    def get_audio_queue(self) -> list[bytes]:
        """Get the list of generated audio data.

        Returns:
            List of WAV binary data.
        """
        return self.audio_data_queue.copy()

    def get_text_queue(self) -> list[str]:
        """Get the list of text inputs.

        Returns:
            List of text strings.
        """
        return self.text_queue.copy()

    def clear_queues(self) -> None:
        """Clear both text and audio data queues."""
        self.text_queue.clear()
        self.audio_data_queue.clear()

    def pop_audio(self) -> tuple[str, bytes] | None:
        """Pop the oldest text and audio data from queues.

        Returns:
            Tuple of (text, audio_bytes) if queues are not empty, None otherwise.
        """
        if self.text_queue and self.audio_data_queue:
            text = self.text_queue.pop(0)
            audio = self.audio_data_queue.pop(0)
            return (text, audio)
        return None

    def __len__(self) -> int:
        """Return the number of items in the queues.

        Returns:
            Number of items in the queues.
        """
        return len(self.audio_data_queue)

    def is_empty(self) -> bool:
        """Check if queues are empty.

        Returns:
            True if queues are empty, False otherwise.
        """
        return len(self.audio_data_queue) == 0
