HOSTNAME = "localhost"

# VOICEVOX
VOICEVOX_PORT = 50021
AUDIO_QUERY_ENDPOINT = f"http://{HOSTNAME}:{VOICEVOX_PORT}/audio_query"
SYNTHESIS_ENDPOINT = f"http://{HOSTNAME}:{VOICEVOX_PORT}/synthesis"

SPEAKER_ID_KASUKABE_TSUMUGI = 8
