HOSTNAME = "0.0.0.0"

# VOICEVOX
VOICEVOX_PORT = 50021
AUDIO_QUERY_ENDPOINT = f"http://{HOSTNAME}:{VOICEVOX_PORT}/audio_query"
SYNTHESIS_ENDPOINT = f"http://{HOSTNAME}:{VOICEVOX_PORT}/synthesis"

# KoboldCpp
KOBOLDCPP_PORT = 50030
KOBOLDCPP_PATH = "./kobold_cpp"
KOBOLDCPP_EXE_FILE = "koboldcpp"
KOBOLDCPP_DOWNLOAD_URL = "https://github.com/LostRuins/koboldcpp/releases/latest/download/koboldcpp-linux-x64"

# Speaker process
VOICE_GENERATOR_PORT = 50100
AUDIO_PLAYER_PORT = 50101

# Messenger process
MESSENGER_PORT = 50050

RESPONSE_STATUS_CODE_SUCCESS = 200
RESPONSE_STATUS_CODE_NOT_FOUND = 404
RESPONSE_STATUS_CODE_ERROR = 500
