# VOICEVOX character
SPEAKER_ID_KASUKABE_TSUMUGI = 8

# Hakurei Reimu
SPEAKER_ID_HAKUREI_REIMU = SPEAKER_ID_KASUKABE_TSUMUGI
VOICE_SPEED_SCALE_HAKUREI_REIMU = 1.2

WORD_DICTIONARY_PATH_HAKUREI_REIMU = "personality/hakurei_reimu/word_dictionary.json"
STORY_SETTINGS_PATH_HAKUREI_REIMU = "personality/hakurei_reimu/story_settings.json"

# Personality settings
SPEAKER_ID = SPEAKER_ID_HAKUREI_REIMU
VOICE_SPEED_SCALE = VOICE_SPEED_SCALE_HAKUREI_REIMU
WORD_DICTIONARY_PATH = WORD_DICTIONARY_PATH_HAKUREI_REIMU
STORY_SETTINGS_PATH = STORY_SETTINGS_PATH_HAKUREI_REIMU
