HOSTNAME = "0.0.0.0"

# VOICEVOX
VOICEVOX_PORT = 50021
AUDIO_QUERY_ENDPOINT = f"http://{HOSTNAME}:{VOICEVOX_PORT}/audio_query"
SYNTHESIS_ENDPOINT = f"http://{HOSTNAME}:{VOICEVOX_PORT}/synthesis"

# Local Voice process
VOICE_GENERATOR_PORT = 50100
AUDIO_PLAYER_PORT = 50101
SPEECH_RECOGNIZER_PORT = 50102

# Outside Voice process
YUKKURI_HOSTNAME = "10.32.1.101"
YUKKURI_PORT = 50200

# Messenger process
MESSENGER_PORT = 50050

RESPONSE_STATUS_CODE_SUCCESS = 200
RESPONSE_STATUS_CODE_NOT_FOUND = 404
RESPONSE_STATUS_CODE_ERROR = 500
